---
- name : install Apache
  hosts :
       RHEL-8
       CENTOS7
  become : yes
  vars :
     Apache : httpd
     Updated : latest
     source_file: /var/www/html/
     destin_file: /var/www/html/
     html_t : /etc/ansible/Playbook/index.j2
  tasks :
  - name : Generage index.html
    template :
     src={{ html_t }}
     dest={{ destin_file }}/index.html
    notify : Restart httpd service after index.html changing
  - copy :
              src={{ source_file }}
              dest={{ destin_file }}
    notify : Restart httpd service after index.html changing
  - dnf :
              name={{ Apache }}
              state={{ Updated }}
    when : ansible_os_family == "RedHat"
  - service :
                name : httpd
                state : started

  handlers :
  - name : Restart httpd service after index.html changing
    service :
          name : httpd
          state : restarted

